version: '3.1'

services:

  database:
    image: postgres:9.5.9
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER= akiyamatsuyoshi
      - POSTGRES_PASS= akiyamatsuyoshi
      - POSTGRES_NAME= akiyamatsuyoshi
  go:
    build: ./
    ports:
      - 80:8080
    links:
    - database
    volumes:
      - .:/go/src/github.com/Akitsuyoshi/goWithDB
